# This workflow will do a clean install of node dependencies, ensure code quality, and perform various tests to ensure high level integration of code.

name: Build and Test

on:
  pull_request:
  label:
  release:

env:
  PROJECT_ID: taptab-cloud-infrastructure

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint, Build and Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js 24.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 24.12.0
          cache: 'npm'
      - name: Clean installing dependencies
        run: npm ci
      - name: Ensuring code quality
        run: npm run lint
      - name: Building application
        run: npm run build --if-present
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  test:
    name: Test cached build
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 24.12.0
          cache: 'npm'
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Unit Testing
        run: npm run test

      # Integration tests need to pull the latest database from the artifacts registry.

      # Setup gcloud CLI
      # Add "id-token" with the intended permissions.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_GITHUB_SA }}'

      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: '406.0.0'
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker us-east1-docker.pkg.dev

      - name: Integration Testing
        env:
          API_PORT: 3000
          NODE_ENV: test
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: npm run test:integration

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: npm-logs
          path: /home/runner/.npm/_logs/
          retention-days: 5
